logging.level:
  root: ERROR
  #pe.interbank: DEBUG
  org.springframework.web: ERROR
  com.microsoft.azure: ERROR
  org.apache.http: ERROR
  io.jaegertracing.internal: ERROR
  org.springframework.boot.actuate: ERROR
  #pe.interbank.rivendell.commons.api.service.ApplicationHealthIndicator: ERROR

spring:
  jackson:
    time-zone: America/Lima
    locale: es_PE

management:
  endpoint:
    metrics:
      enabled: false
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,edoras-features

edoras.account.creation-adapter:
  features:
    anyFeature: true # FIXME example config
  configuration:
    biometryUrl: https://identity.acceptance.interbank.pe/#/auth?token=${token.access_token}
    biometry:
      timeout: 10s
      pool:
        size: 32
        queue: 64
        queue-timeout: 10s
        name: blacklist-dynamic-search-client
    transfers:
      timeout: 30s
      pool:
        size: 32
        queue: 64
        queue-timeout: 30s
        name: internal-transfers
    oauth2:
      timeout: 5s
      grantType: client_credentials
      scope: "token:application"
  apps.config:
    applicationConfigurationHost: http://theshire-applications.theshire-qa.svc.cluster.local:8080
    applicationHealthEndpoint: http://theshire-applications.theshire-qa.svc.cluster.local:8080/actuator/health
  crypto:
    algorithm: PBKDF2WithHmacSHA256
    salt: salt
    secret: secret
  apis:
    encryptionEnabled: false
    customerEnrolled:
      endpoint: http://theshire-identity.theshire-qa.svc.cluster.local:8080/identity/customer?identityDocumentType={identityDocumentType}&identityDocumentNumber={identityDocumentNumber}&identityCompany={identityCompany}&identityChannel={identityChannel}
    bioSecurityURL:
      endpoint: https://apis.uat.interbank.pe/bio-security/v1/oauth2/token
    bioSecurityStatus:
      endpoint: https://apis.uat.interbank.pe/bio-security/v1/transaction/{transactionId}
      subscription: b18be3bcfa8e41f2ac4ef6d9406ef157
    customerDocument: http://theshire-customers.theshire-qa.svc.cluster.local:8080/internal/customers?identityDocumentNumber={identityDocumentNumber}&identityDocumentType={identityDocumentType}
    cashInToken:
      endpoint: http://gondor-izipay-integrations.gondor-qa.svc.cluster.local:8080/izipay/authentication
      requestSource: ECOMMERCE
      apiVersion: "v1"
      apiForceSync: true
      merchantCodePen: 4004345
      publicKeyPen: VErethUtraQuxas57wuMuquprADrAHAb
      merchantCodeUsd: 6001835
      publicKeyUsd: VErethUtraQuxas57wuMuquprADrAHAb
    cashInValidation:
      endpoint: http://theshire-applications.theshire-qa.svc.cluster.local:8080/config/{application_id}/{property}
    cashInCustomer:
      endpoint: http://theshire-customers.theshire-qa.svc.cluster.local:8080/customers/info
    cashInTransaction:
      endpoint: http://gondor-izipay-integrations.gondor-qa.svc.cluster.local:8080/izipay/{accountId}/cash-in-transfer
      headers:
        apiVersion: "v1"
        apiForceSync: true
      values:
        accountNumberPEN: "1007001336670"
        accountNumberUSD: "1007001336670"
        requestSource: ECOMMERCE
    cashInTransactionCancellation:
      endpoint: http://gondor-izipay-integrations.gondor-qa.svc.cluster.local:8080/izipay/cancellation
      apiForceSync: true
      apiVersion: "v1"
    cashInCardAssignmentValidation:
      endpoint: http://theshire-accounts.theshire-qa.svc.cluster.local:8080/accounts/card-assignment/validations
    cashInPlainCardInformation:
      endpoint: http://theshire-cards.theshire-qa.svc.cluster.local:8080/cards/virtual-card-info
    oauth2-authentication:
      endpoint: https://apiqa.digital.interbank.pe/security/v1/oauth/token

  applications:
    - name: tunki
      applicationId: LhFiDhhGcVD67zvA
      secret: E8aszcUX7eFsupBp
      subscriptionKey: e547435595fd4ac3a4291aa456e3d43d
      logoUrl: ""
      backgroundUrl: ""
      businessName: TUNKI
      identityChannel: OPB
      identityCompany: INTERBANK
      clientId: e0c06fb9-49c9-4d61-b444-fe4d1c3e7602
    - name: sixflags
      applicationId: p2kvguvRCYgkwoxk
      secret: gChffp8tRT7fd8Ve
      subscriptionKey: e547435595fd4ac3a4291aa456e3d43d
      logoUrl: ""
      backgroundUrl: ""
      businessName: SIXFLAGS
      identityChannel: OPB
      identityCompany: INTERBANK
      clientId: e0c06fb9-49c9-4d61-b444-fe4d1c3e7602
    - name: app
      applicationId: vFaCse3R9RDoJUGU
      secret: zPf8h48xwqgB4yzT
      subscriptionKey: e547435595fd4ac3a4291aa456e3d43d
      logoUrl: ""
      backgroundUrl: ""
      businessName: APP
      identityChannel: OPB
      identityCompany: INTERBANK
      clientId: e0c06fb9-49c9-4d61-b444-fe4d1c3e7602
    - name: izipay
      applicationId: RzZYuFa7Fd8yb4Ch
      secret: '{cipher}AQBWgE71rQKFB+r/Eau0wNDNR67TXBNEO+GoDFzDn0fhQylg5i3I7lyIUYAZEgSIyWcjmBjmx3U11unAwh1aUctOp8RvViaQnOD6OetlbVEPd8qfW7cZ+vPABcsudAHIieL4uSP4Kck8nRTzqWTdPktILC7wv4EHPq498d0nbgPZ7oOuf2RSaDWMYHFF65FecmbICepumTNdPXAcSYjIyM7g1DkacFAuQ4uDcyQxqUstyss7YAZw+6ItbV2bhYXX7jAXEPvO5JNNq7tFxqYSzg6XU5NKpD27/76GOZQAklW4XNYqYxb8rZE2rV1dT1HY0604AEaxjtdP+HgHCyLSv/plPo3ZV1bAd5d4ymGBLFEPYx9SMzaDesPa8EAezEFmlc5k1dTuaRN5FerwHEDfLvQL'
      subscriptionKey: e547435595fd4ac3a4291aa456e3d43d
      logoUrl: "https://iziweb001b.s3.amazonaws.com/webresources/img/logo.png"
      backgroundUrl: "https://www.revistagptwperu.com/wp-content/uploads/2023/02/7.-izipay-1-1.jpg"
      businessName: IZIPAY
      identityChannel: OPB
      identityCompany: INTERBANK
      clientId: e0c06fb9-49c9-4d61-b444-fe4d1c3e7602
    - name: kambista
      applicationId: ehHRWCZ6j9xaxw33
      secret: 4UhgnHLTrpvpezGc
      subscriptionKey: e547435595fd4ac3a4291aa456e3d43d
      logoUrl: ""
      backgroundUrl: ""
      businessName: KAMBISTA
      identityChannel: OPB
      identityCompany: INTERBANK
      clientId: e0c06fb9-49c9-4d61-b444-fe4d1c3e7602
    - name: izipayMobile
      applicationId: nOTIwreqaRexehOk
      secret: yltotEguqEChedrA
      subscriptionKey: e547435595fd4ac3a4291aa456e3d43d
      logoUrl: ""
      backgroundUrl: ""
      businessName: "IZIPAY MOBILE"
      identityChannel: OPB
      identityCompany: INTERBANK
      clientId: e0c06fb9-49c9-4d61-b444-fe4d1c3e7602
    - name: niubiz
      applicationId: Niml3hlchOthospO
      secret: 93qXrVraG3huyNvZ
      subscriptionKey: e547435595fd4ac3a4291aa456e3d43d
      logoUrl: ""
      backgroundUrl: ""
      businessName: NIUBIZ
      identityChannel: OPB
      identityCompany: INTERBANK
      clientId: e0c06fb9-49c9-4d61-b444-fe4d1c3e7602
    - name: buda
      applicationId: muganuzesOchugIY
      secret: FecriDruFrutheta
      subscriptionKey: e547435595fd4ac3a4291aa456e3d43d
      logoUrl: ""
      backgroundUrl: ""
      businessName: BUDA
      identityChannel: OPB
      identityCompany: INTERBANK
      clientId: e0c06fb9-49c9-4d61-b444-fe4d1c3e7602
    - name: belcorp
      applicationId: xRBXxYhLcpM3HN39
      secret: E8aszcUX7eFsupBp
      subscriptionKey: e547435595fd4ac3a4291aa456e3d43d
      logoUrl: ""
      backgroundUrl: ""
      businessName: BELCORP
      identityChannel: OPB
      identityCompany: INTERBANK
      clientId: e0c06fb9-49c9-4d61-b444-fe4d1c3e7602
